package org.itmo.bfs.impl;

import java.util.LinkedList;
import org.itmo.Graph;
import org.itmo.bfs.Bfs;

public class SimpleBfs implements Bfs {

    //Generated by ChatGPT
    @Override
    public void bfs(Graph graph, int startVertex) {
        boolean[] visited = new boolean[graph.getSize()];

        LinkedList<Integer> queue = new LinkedList<>();

        visited[startVertex] = true;
        queue.add(startVertex);

        var adjList = graph.getAdjList();
        while (!queue.isEmpty()) {
            startVertex = queue.poll();

            for (int n : adjList[startVertex]) {
                if (!visited[n]) {
                    visited[n] = true;
                    queue.add(n);
                }
            }
        }
    }
}
